behaviors:
  ArcherAI:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 2048
      learning_rate: 0.0005
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity: 
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
    self_play:
      save_steps: 50000
      team_change: 100000
      swap_steps: 2000
      window: 20
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
    max_steps: 30000000
    time_horizon: 1000
    summary_freq: 30000
